class NewStudent {
  String firstName = '';
  String middleName = '';
  String lastName = '';
  String profileImage = '';
  String aadhaarNumber = '';
  String aadhaarFile = '';
  String marksheet10 = '';
  String marksheet12 = '';
  String transferCertificate = '';
  String idProof = '';
  String rollNo = '';
  String registrationNo = '';
  int? classId;
  int? sectionId;
  DateTime? admissionDate;
  String? lateralAdmission;
  String? admissionCategory;
  String? studentStatus;
  DateTime? dob;
  String? gender;
  String? bloodGroup;
  String nationality = '';
  String phone = '';
  String altPhone = '';
  String email = '';
  String password = '';
  String address = '';
  String city = '';
  String district = '';
  String state = '';
  String pincode = '';
  String fatherName = '';
  String fatherOccupation = '';
  String fatherPhone = '';
  String motherName = '';
  String motherOccupation = '';
  String motherPhone = '';
  String guardianName = '';
  String guardianRelation = '';
  String guardianPhone = '';
  String allergies = '';
  String medications = '';
}
